"""empty message

Revision ID: 2ef64e224733
Revises: 99a51bb81b9f
Create Date: 2019-10-18 15:22:14.015747

"""

# revision identifiers, used by Alembic.
revision = '2ef64e224733'
down_revision = '99a51bb81b9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('token', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.ForeignKeyConstraint(['name'], ['user.name'], ),
    sa.PrimaryKeyConstraint('token')
    )
    ### end Alembic commands ###
