"""empty message

Revision ID: 3965bf85f7ca
Revises: bb3b556a2d5e
Create Date: 2019-10-19 16:54:22.466985

"""

# revision identifiers, used by Alembic.
revision = '3965bf85f7ca'
down_revision = 'bb3b556a2d5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('google_ref', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'google_ref')
    ### end Alembic commands ###
