"""empty message

Revision ID: 47cd5fe99d32
Revises: 
Create Date: 2020-04-13 18:27:30.047720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cd5fe99d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('google_ref', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postcode')
    )
    op.create_table('forecast',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('recorded_timestamp', sa.DateTime(), nullable=False),
    sa.Column('weather_timestamp', sa.DateTime(), nullable=False),
    sa.Column('apparent_temperature', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.String(length=1000), nullable=True),
    sa.Column('dew_point', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('icon', sa.String(length=1000), nullable=True),
    sa.Column('ozone', sa.Float(), nullable=True),
    sa.Column('precip_accumulation', sa.Float(), nullable=True),
    sa.Column('precip_intensity', sa.Float(), nullable=True),
    sa.Column('precip_probability', sa.Float(), nullable=True),
    sa.Column('precip_type', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_bearing', sa.Float(), nullable=True),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'recorded_timestamp', 'weather_timestamp')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('forecast')
    op.drop_table('location')
    ### end Alembic commands ###
