"""empty message

Revision ID: 76dd23886f3a
Revises: 2ba8ebc9fb18
Create Date: 2019-10-19 16:27:58.493028

"""

# revision identifiers, used by Alembic.
revision = '76dd23886f3a'
down_revision = '2ba8ebc9fb18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    ### end Alembic commands ###
