"""empty message

Revision ID: 78fe594f7b5b
Revises: 
Create Date: 2020-04-26 18:20:38.033154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fe594f7b5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('location', sa.Column('place', sa.String(length=10), nullable=False))
    # op.create_unique_constraint(None, 'location', ['place'])
    # op.drop_column('location', 'postcode')
    ### end Alembic commands ###
    op.alter_column('location', 'postcode', new_column_name='place')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('location', sa.Column('postcode', sa.VARCHAR(length=10), nullable=False))
    # op.drop_constraint(None, 'location', type_='unique')
    # op.drop_column('location', 'place')
    # ### end Alembic commands ###
    op.alter_column('location', 'place', new_column_name='postcode')