"""empty message

Revision ID: af54ba22a492
Revises: 772612d1de75
Create Date: 2020-05-11 16:04:47.076240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af54ba22a492'
down_revision = '772612d1de75'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered')
    ### end Alembic commands ###
