"""add preferences table

Revision ID: f262204a77b9
Revises: af54ba22a492
Create Date: 2020-05-18 12:53:05.123738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f262204a77b9'
down_revision = 'af54ba22a492'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_start', sa.Integer(), nullable=True),
    sa.Column('day_end', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interests',
    sa.Column('activity_name', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_name'], ['activity.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('activity_name', 'user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interests')
    op.drop_table('preferences')
    op.drop_table('activity')
    ### end Alembic commands ###
