"""increase place string length

Revision ID: 78fe594f7b5b
Revises: 
Create Date: 2020-04-26 18:20:38.033154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'manual_length_change'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('location', sa.Column('place', sa.String(length=10), nullable=False))
    # op.create_unique_constraint(None, 'location', ['place'])
    # op.drop_column('location', 'postcode')
    ### end Alembic commands ###
    op.alter_column('location', 'place', existing_type=sa.String(length=10),
                    type_=sa.String(100),
                    existing_nullable=False)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('location', sa.Column('postcode', sa.VARCHAR(length=10), nullable=False))
    # op.drop_constraint(None, 'location', type_='unique')
    # op.drop_column('location', 'place')
    # ### end Alembic commands ###
    op.alter_column('location', 'place', existing_type=sa.String(length=100),
                    type_=sa.String(10),
                    existing_nullable=False)